name: StrawBattle
version: 0.0.2
description: Mini-jeu de combat avec des boules (enflammée)
author: Eclixal
main: bzh.strawberry.strawbattle.StrawBattle
api-version: 1.16
commands:
  forcestart:
    description: Pour forcer le lancement du jeu
    permission: strawbattle.forcestart
    permission-message: Vous n'êtes pas autorisé a effectuer cette commande !
    aliases:
      - fs
      - force
  github:
    description: Pour avoir toutes les infos de la StrawBerryCorp
    aliases:
      - git
      - source